name: Develop Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:

    runs-on: ubuntu-18.04
    environment: develop

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run poetry image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.8

    - name: install dependencies
      run: poetry install

    - name: Test with pytest
      run: poetry run pytest --cov=simple_dependency_injection --cov-config=.coveragerc --cov-report=xml

    - name: Override Coverage Source Path for Sonar
      run: sed -i 's/\/home\/runner\/work\/simple-dependency-injection\/simple-dependency-injection\//\/github\/workspace\//g' test-reports/cov.xml

    - name: Set Correct Sonar Version
      run: export VERSION=$(grep version pyproject.toml | sed 's/version\s*=\s*"//' | sed 's/"//') && echo "sonar.projectVersion=${VERSION}" >> sonar-project.properties

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: upload lib
      env:
        USER: ${{ secrets.PIP_USER }}
        PASSWORD: ${{ secrets.PIP_PASSWORD }}
      run: poetry config repositories.test https://test.pypi.org/legacy/ && poetry build && poetry publish -r test --username $USER --password $PASSWORD
