name: Pull Request Pipeline

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    environment: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run poetry image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.8

    - name: install dependencies
      run: poetry install

    - name: Test with pytest
      run: poetry run pytest --cov=simple_dependency_injection --cov-config=.coveragerc --cov-report=xml

    - name: Override Coverage Source Path for Sonar
      run: sed -i "s/<source>\/home\/runner\/work\/repo<\/source>/<source>\/github\/workspace<\/source>/g" /home/runner/work/repo/test-reports/cov.xml

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
